タイムラインにおけるPlatCellの作成
stlatica/stlatica pull request #171
Opened 2023-10-28 19:37 UTC by nobuchi

# Issue

Closes #125

# Overview

タイムライン上の1つのPlatのセルとして、アイコン、ユーザ名、ユーザID、Plat内容、返信数、シェア数、いいね数を表示するUIを作成しました。

# Operation Verification

# Check List

- [x] セルフレビューをした(must)
- [ ] テストコードを記載した
- [ ] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [x] 適切なLabelを設定した(e.g. frontend, documentation)
- [x] 適切なProjectを設定した(e.g. Minimum Structure)

# Others

2023-10-29 13:16 UTC, para7 requested changes
@nobuchi 
見た目等はとりあえずこんな感じでOKです、ありがとうございます！

実装面で気になった箇所があるので以下の修正をお願いします:

---

幅の指定はコンポーネント内に入れたくないので、最大幅使うように設定をお願いします。

こうするとladleの表示が崩れると思いますが、stories.tsx 内で 幅設定した div で囲っておいてください。

```jsx
<div style={{width: "300px"}}>
  <PlatCell>
</div>
```

ladleも数パターンぐらい表示サンプル作ってあると良さそうです。幅の数値変えてコピペするだけなのですぐに用意できると思います。

2023-10-29 13:18 UTC, para7 commented on packages/frontend/src/components/common/PlatCell/PlatCell.tsx
> +    <div style={{ width: "310px", padding: "2%", backgroundColor: "#373737", color: "#FFFFFF" }}>
ここで310固定になってしまっているので、これを指定するのをやめると全幅使えるようになると思われます。どこか崩れたら都度調整で。

2023-11-04 19:33 UTC, nobuchi commented
@para7 

component内で指定していたwidthの値をstoriesで指定するようにしました。
この関係でpaddingの一部を % による指定から px の指定に変更しました。

確認お願いします。

2023-11-05 12:22 UTC, para7 approved these changes
@nobuchi 
OKです！ありがとうございます！

#184 で起票しましたが、今後tailwindへの置き換えをお願いいたします！

2023-11-05 12:22 UTC, merged