Edit profile/#130
stlatica/stlatica pull request #188
Opened 2023-11-05 15:18 UTC by nobuchi

# Issue

Closes #130

# Overview

EditProfile画面のレイアウトを作成しました。
css は tailwind を使用しています。

![image](https://github.com/stlatica/stlatica/assets/79183832/f3be096f-2a71-4d8c-8fb6-976969471dc3)

# Operation Verification

# Check List

- [ ] セルフレビューをした(must)
- [ ] テストコードを記載した
- [ ] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [x] 適切なLabelを設定した(e.g. frontend, documentation)
- [x] 適切なProjectを設定した(e.g. Minimum Structure)

# Others

2023-11-12 13:44 UTC, para7 requested changes

2023-11-12 13:44 UTC, para7 commented on packages/frontend/src/app/EditProfile/NameEditor.tsx
> +      <div>textbox</div>
見た目だけでよいと言ったのが悪いんですが、dom属性は最低限合わせておきたいので入力欄はinputでお願いいたします！ (dom要素…divとかinputとかbuttonとか)

https://flowbite.com/docs/forms/floating-label/

↑これの floating label のスタイルとかよさそうなかんじがしますね

2023-11-25 19:48 UTC, nobuchi commented
![image](https://github.com/stlatica/stlatica/assets/79183832/497a947d-df8c-4263-8916-3b3b6919e947)

![image](https://github.com/stlatica/stlatica/assets/79183832/4c3bcde2-297b-4e34-b93c-b5e7b545bba4)


@para7 

テキスト編集のコンポーネントを作成し、EditProfile画面に実装しました。
ladle の TextEditor についても確認していただきたいです。

コンポーネントのパラメータは以下のとおりです。

- componentId : コンポーネント固有のID
- defaultValue : ページを開いたときからテキストボックスに入力されている内容
- maxlength : 文字数制限
- title : 編集する対象 ( Name や Self-Introduction など )

1ページで componentId の部分が同じである TextEitor を複数回呼び出すと、label 要素の動作がおかしくなりました。
componentIdについてはコンポーネント側で生成することも考えましたが、uuid / ulid / cuid のどれを使うべきかわからなかったので外部から与えるようにしました。

2023-11-30 13:42 UTC, para7 requested changes
@nobuchi 
挙動は現段階ではこんな感じでよさそうです！ありがとうございます！
機能的には残りの文字数表示とか必要になりそうですが、色々決めないといけないため今は作らずで大丈夫です。

ID部分だけコメント書いたので修正お願いします！

2023-11-30 13:42 UTC, para7 commented on packages/frontend/src/components/common/TextEditor/TextEditor.tsx
> +  componentId,
@nobuchi 
ID、画面全体で重複がないように外から指定するのはしんどいし本質からずれたデータを要求されることになってしまうので、内部で生成するほうがよさそうですね。

ID生成アルゴリズムですが、フロントで一時的に使うだけなら性能面あまり必要ないと思われるのでバンドルサイズに注目するとnanoidが良さそうです。（scrapboxに書いたので確認ください）（ぶっちゃけこの程度の要件なら Math.random() でも足りそうですが、他で使えそうなのでnanoid利用で大丈夫です。）

----

腐敗防止層として、CreateID() みたいな関数を挟んで利用してみてください。

src/features/acl/CreateID.ts あたりにファイルを追加して

> src/features/acl/CreateID.ts

```typescript
export const CreateID = () => {
 return NanoID(); 
}
```

のように余計な処理はつけずそのままラッピングします。CreateIDを噛ませておくことで、後でnanoidに問題が見つかってもすぐシステム全体で差し替えできます。

---

コンポーネントでは useState か useRef を使い、コンポーネント内部で生成します。

stateだとレンダリングに絡んでくるように見えてしまうので、refの方がよいかもしれません

> TextEditor.tsx

```typescript
const componentId = useRef( CreateID() );

<textarea
  id={componentId.current}
```

2023-12-30 13:15 UTC, nobuchi commented
@para7 

テキストボックスのコンポーネントIDをnanoidで生成できるようにしましたので確認をお願いします。

スナップショットテストは
components/common/TextEditor/TextEditor.test.tsx
の中身をコメントアウトして封じてあります。

2023-12-31 13:16 UTC, para7 approved these changes
@nobuchi 

チェックしました。ちょっとした修正と引用元の記載依頼ですが、対応できそうなら対応お願いします！

2023-12-31 13:16 UTC, para7 commented on packages/frontend/src/components/common/TextEditor/TextEditor.tsx
> +        className="peer block h-full w-full appearance-none rounded-lg border border-white bg-transparent p-3 px-2.5 pb-2.5 pt-4 text-sm text-gray-800 focus:border-blue-600 focus:outline-none focus:r
今更ではあるんですが、どこかから引用した場合は引用元をコメントで記載しておいていただけると助かります！
最初に言ってなかったのでもし不明でしたら非対応で大丈夫です！

2023-12-31 13:16 UTC, para7 commented on packages/frontend/src/app/EditProfile/page.tsx
> +            <SubmitButton className="w-[85px]">Save</SubmitButton>{" "}
ここに入っている

> {" "}

ですが、意図せずlintで紛れ込んだものに見えます。
不要なものだと思いますので、これらが混入していた場合は消すようにお願いします！

（もし削除してデザインが崩れる場合は、この方法ではなくpaddingやmarginでの調整をお願いします）

2024-01-01 19:47 UTC, nobuchi commented on packages/frontend/src/components/common/TextEditor/TextEditor.tsx
> +        className="peer block h-full w-full appearance-none rounded-lg border border-white bg-transparent p-3 px-2.5 pb-2.5 pt-4 text-sm text-gray-800 focus:border-blue-600 focus:outline-none focus:r
対応しました！

2024-01-01 19:48 UTC, nobuchi commented on packages/frontend/src/app/EditProfile/page.tsx
> +            <SubmitButton className="w-[85px]">Save</SubmitButton>{" "}
対応しました！

デザインは崩れずに済みました

2024-01-01 19:52 UTC, nobuchi commented on packages/frontend/src/components/common/TextEditor/TextEditor.tsx
componentId の型が any であり lint の警告が出ていたため、string型を明示するようにしました。

2024-01-01 19:53 UTC, merged