丸いユーザアイコンコンポーネント追加
stlatica/stlatica pull request #192
Opened 2023-11-12 13:45 UTC by LR-nemusuke

# Issue

Closes #122

# Overview

ユーザアイコン画像を丸い形状で表示する。
![image](https://github.com/stlatica/stlatica/assets/96586585/7512f7ed-007d-4e63-ade5-be99936b12b4)

# Operation Verification

# Check List

- [ ] セルフレビューをした(must)
- [ ] テストコードを記載した
- [ ] 動作検証の結果を記載した

# Others

2023-11-13 04:15 UTC, para7 commented
lint調整が必要のため @para7 対応

2023-11-19 13:01 UTC, para7 requested changes
@LR-nemusuke 
すみません、お待たせいたしました。いくつか修正をお願いします！

2023-11-19 13:01 UTC, para7 commented on packages/frontend/src/components/common/UserIcon/sample/UserIconBase64Sample1.ts
> +  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUF
サンプル画像ですが、権利的に100%問題のないものに差し替えをお願いします

2023-12-07 16:18 UTC, LR-nemusuke commented
@para7 下記内容を修正しました。

- propからサイズ指定を削除
- サンプルコードの追加(100px, 300px, 500px)、書き方をTailwindに統一
- 画像の差し替え(自身で撮影した画像)
![image](https://github.com/stlatica/stlatica/assets/96586585/cc6678cb-ed57-431d-8c0a-ddbf88a60fd4)
- アイコンを丸くする部分をTailwindに変更
長方形画像を入力とすると上記のように楕円になる状態ですので、画像の切り取り機能かまたは入力を正方形のみに限定する必要があるかと思います。

ご確認のほどよろしくお願いします。

2023-12-10 12:45 UTC, para7 approved these changes
@LR-nemusuke 
修正ありがとうございます！

> 長方形画像を入力とすると上記のように楕円になる状態ですので、画像の切り取り機能かまたは入力を正方形のみに限定する必要があるかと思います。

こちらですがimageタグ側で aspect-square を指定しアスペクト比を1:1に、w-fullとh-fullを指定し親要素の全幅取るようにして修正してみました。確認してみてください。

---

また、初めてだと思いますのでapproveのみに留めておきました。せっかくなのでマージもやってみてください。（マージボタンを押すだけではありますが）

2023-12-20 12:01 UTC, merged