Login scene/#237
stlatica/stlatica pull request #292
Opened 2024-02-02 08:11 UTC by LRun99

# Issue
#237 

# Overview

@para7 
下図のようなログイン画面の外観を作成しました。
![image](https://github.com/stlatica/stlatica/assets/96586585/f49ec476-9a69-46a6-ba0a-8b316b1efb33)

詳細：
Buttonのところにcomponents/LoginButtonをSubmitButtonを流用して、components/othersのところに画面外観を作成しました。
LoginButtonがクリックされたときの動作は現在はコンソールにクリックされた旨を表示するのみです。

# Operation Verification

# Check List

- [ ] セルフレビューをした(must)
- [ ] テストコードを記載した
- [ ] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [ ] 適切なLabelを設定した(e.g. frontend, documentation)
- [ ] 適切なProjectを設定した(e.g. Minimum Structure)

# Others

2024-02-04 12:00 UTC, para7 requested changes
@LRun99 
いくつか確認&修正お願いします！

2024-02-07 17:08 UTC, LRun99 commented on packages/frontend/src/components/others/LoginScene/index.ts
> +export * from "./LoginScene";
app/login/page.tsxに作り直しました。

2024-02-07 17:10 UTC, LRun99 commented on packages/frontend/src/components/others/LoginScene/LoginScene.tsx
> +      <div className="h-24 w-80 bg-gray-800 p-6 text-white">
margin使いながら調整してみたので一度確認して頂きたいです…！よろしくお願いします！

2024-02-12 09:59 UTC, para7 requested changes
@LRun99 
スタイルの付け方がうまく伝わってなかったのが悪いんですが、コメントしたイメージで修正してみてください！

2024-02-16 13:06 UTC, para7 commented
@LRun99 
vrtエラーの修正方法は以下になります

0. docker, make のインストールを行う 
1. mainブランチをマージしてくる
2. make vrt で差分を確認する
3. 問題なければ make vrt/update で更新をかける
4. git commit

2024-02-17 15:23 UTC, para7 requested changes
@LRun99 

divは2階層で十分ですのでそこの修正と、ひとつ前に単発コメントで記載したビルドの修正をお願いします！

2024-02-17 15:23 UTC, para7 commented on packages/frontend/src/app/login/page.tsx
> +      <div className="flex w-[50%] min-w-[400px] max-w-[600px] flex-col">
```suggestion
      <div className="flex w-[80%] min-w-[300px] max-w-[800px] flex-col justify-center gap-6">
```

縦幅は個別でマージン設定の必要はなく、 flexbox での調整で十分となります

2024-02-17 15:23 UTC, para7 commented on packages/frontend/src/app/login/page.tsx
> +        <div className="mt-[50%] space-y-6">
こちらは不要となります。_

今回行うのは横幅の設定・縦配置の設定で大まか2属性なので、divが3階層以上になっていたら違和感を持てるようになるとgoodです！

2024-03-03 09:53 UTC, para7 approved these changes

2024-03-03 09:53 UTC, merged