plat cellの不足要素追加/#355
stlatica/stlatica pull request #386
Opened 2024-03-30 02:21 UTC by nobuchi

# Issue

Closes #355 

# Overview

@para7 

PlatCellのコンポーネントに以下をを加えました。

- 投稿日時
- アイコンの表示
- 右上のメニュー

使用したMantineのMenu要素はデフォルトで真下にメニューを表示するそうですが、右上のメニューに関して表示位置が画面左上になってしまいます。修正方法をご存知であれば教えていただきたいです。

https://mantine.dev/core/menu/

# Operation Verification

![image](https://github.com/stlatica/stlatica/assets/79183832/26e82a70-035a-4255-a5d4-ce34a27e45c4)

# Check List

- [x] セルフレビューをした(must)
- [ ] テストコードを記載した
- [x] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [ ] 適切なLabelを設定した(e.g. frontend, documentation)
- [ ] 適切なProjectを設定した(e.g. Minimum Structure)

# Others

2024-03-31 11:53 UTC, nobuchi commented
@para7 

CIが通りましたので確認をお願いいたします

2024-03-31 15:47 UTC, para7 requested changes
@nobuchi 
レビューしました。確認お願いします！

2024-03-31 15:47 UTC, para7 commented on packages/frontend/src/components/common/PlatCell/PlatCell.tsx
> +  const formatDateLocale = (date: Date): string => {
PlatCellのコンポーネント内で関数定義をするとレンダリングのたびに生成されます。
この関数は特に文脈への依存がなく、再生成が必要ない内容ですので関数の外に移動でお願いします。

このファイルでいうと props の定義前、つまり7行目あたりが妥当ですね。

// この程度の処理であれば、別のファイルに分ける対応まではしなくていいとは思います

2024-03-31 15:47 UTC, para7 commented on packages/frontend/src/components/common/PlatCell/PlatCell.tsx
> +    return date.toLocaleString();
toLocaleString ですが内部的にIntl.DateTimeFormatが呼び出されるようです。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

実装依存になると嫌なので、だったら最初から直接Intl.DateTimeFormatを使ったほうがよさそうにも感じますね。

が、そのIntl.DateTimeFormatは取り扱いを間違えるとパフォーマンスに問題を抱える可能性があるようです

https://zenn.dev/mazamachi/articles/js-intl-date-time-format-performance

このあたり調査検証お願いできますでしょうか？

あるいは方法がよくわからない / 面倒なので一旦後回しにしたい等であれば TODO コメントを発行しておく形でも問題ありません。

2024-03-31 15:47 UTC, para7 commented on packages/frontend/src/components/others/DateTime/DateTime.tsx
> +  readonly formatDate: (date: Date) => string;
毎回毎回フォーマット関数を渡すのが大変なのと、あっちのタイムラインとこっちのタイムラインで表示を2種出し分けたいケースが特に思いつかないので、propで注入せずコンポーネント内部で実装してしまって問題なさそうに感じます。

// むしろ渡すフォーマット関数を間違える可能性がある＝バグが入り込む余地が増える可能性すらあるかなと。

2024-04-01 09:32 UTC, para7 commented
> 使用したMantineのMenu要素はデフォルトで真下にメニューを表示するそうですが、右上のメニューに関して表示位置が画面左上になってしまいます。修正方法をご存知であれば教えていただきたいです。

こちら読み飛ばしてましたが、今すぐは原因分からないですね。ひとつずつ解読していかないとダメそうです。
アンカーが外れてるか、想定外の場所に適用されてしまっているのだとは思いますが…。

本PRは見た目要素の追加がメインなのと、メニューの表示は今すぐ動かなくても支障ないので、原因解明が難しければバグ起票しつつマージでも大丈夫です。

2024-04-21 11:06 UTC, nobuchi commented on packages/frontend/src/components/common/PlatCell/PlatCell.tsx
> +    return date.toLocaleString();
こちらの内容は興味があるのでやってみたいと思うので、GW中に時間を取って取り組みたいと思います。なのでもうしばらくお時間をいただきたいです。

2024-05-03 15:18 UTC, nobuchi commented
> > 使用したMantineのMenu要素はデフォルトで真下にメニューを表示するそうですが、右上のメニューに関して表示位置が画面左上になってしまいます。修正方法をご存知であれば教えていただきたいです。
> 
> こちら読み飛ばしてましたが、今すぐは原因分からないですね。ひとつずつ解読していかないとダメそうです。 アンカーが外れてるか、想定外の場所に適用されてしまっているのだとは思いますが…。
> 
> 本PRは見た目要素の追加がメインなのと、メニューの表示は今すぐ動かなくても支障ないので、原因解明が難しければバグ起票しつつマージでも大丈夫です。

mantine に用意されているMenuタグの中で react-icons の MdMoreHoriz を呼び出しているのが悪かったようです。

以下のように div で MdMoreHoriz を囲むとボタン直下にメニューが現れるようになりました。

```
<Menu>
  <Menu.Target>
    <div>
      <MdMoreHoriz />
    </div>
  </Menu.Target>
  <Menu.Dropdown>
    <Menu.Item>Delete this plat</Menu.Item>
    <Menu.Item>Mute this user</Menu.Item>
  </Menu.Dropdown>
</Menu>
```

2024-05-04 09:50 UTC, closed without merging

2024-05-04 09:51 UTC, nobuchi commented
remixへの移行に伴い、こちらの作業に関するブランチは作り直します。