plat cellの不足要素追加_remix_パーミッションコミット除去版/#355
stlatica/stlatica pull request #453
Opened 2024-05-25 18:22 UTC by nobuchi

# Issue
Closes https://github.com/stlatica/stlatica/issues/355

# Overview
#431 に含んでしまったパーミッション変更の差分を取り除いたブランチを作成しました。

PlatCellのコンポーネントに以下を加える作業を行いました。

- [x] 投稿日時
- [x] アイコンの表示
- [x] 右上のメニュー

---

> toLocaleString ですが内部的にIntl.DateTimeFormatが呼び出されるようです。
> 
> https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
> 
> 実装依存になると嫌なので、だったら最初から直接Intl.DateTimeFormatを使ったほうがよさそうにも感じますね。
> 
> が、そのIntl.DateTimeFormatは取り扱いを間違えるとパフォーマンスに問題を抱える可能性があるようです
> 
> https://zenn.dev/mazamachi/articles/js-intl-date-time-format-performance
> 
> このあたり調査検証し修正お願いできますでしょうか？

#386 のこちらについて、Intl.DateTimeFormatのインスタンス生成を繰り返さないように注意して実装を行いました。

インスタンスの生成を繰り返したときとそうでないときの実装は、[plat_cell_bad_impl/#355](https://github.com/stlatica/stlatica/tree/plat_cell_bad_impl/%23355)というブランチのladleにて、
common > PlatCell > date bad/good impl に行いました。

具体的な時間の測り方はわからなかったのですが、platを3000件読み込ませたところ、あまり差は見受けられませんでした。

---

@para7 

度重なるブランチの作り直しとなり恐縮ですが、ご確認お願いいたします。

# Operation Verification

![image](https://github.com/stlatica/stlatica/assets/79183832/69535265-4a09-46b6-94a5-234b2db7307c)

# Check List

- [x] セルフレビューをした(must)
- [ ] テストコードを記載した
- [x] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [x] 適切なLabelを設定した(e.g. frontend, documentation)
- [ ] 適切なProjectを設定した(e.g. Minimum Structure)

# Others

2024-05-27 06:27 UTC, para7 requested changes
@nobuchi 
サジェストした項目のみの軽微な修正ですが、確認お願いします！

---

Intl.DateTimeFormat ですが、この書き方であれば呼び出されるのは1回のみになり、確認をお願いしていたパフォーマンス面は大丈夫そうです！ありがとうございました！

2024-05-27 06:27 UTC, para7 commented on packages/frontend/remix/e2e/ladle-snapshots/snapshot.test.ts-snapshots/common--platcell--1行の-plat-visual-snapshot-linux.png
私の検討不足もあり、日付部分にちょっと色々修正した方がよさそうな事項が見つかりました。

致命的な問題はないので今回の時点ではこれでOKです。
次回定例ですり合わせしたのち、別途チケットに切ります。

2024-05-27 06:27 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatCell.tsx
> +        <div>{formatter.format(dateObj(date))}</div>
```suggestion
        <div>{formatter.format(new Date(date))}</div>
```

2024-05-27 06:27 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatCell.tsx
> +};
このラッピング、ほとんど意味を成していないので不要な感じがします。

直接 new Date() でよさそう。


```suggestion
```

2024-05-27 06:27 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatCell.tsx
> +  timeZone: "Asia/Tokyo",
将来的には、タイムゾーンはユーザーの利用環境から取得したいところですね。
とりあえずは直打ちで問題ないですが、頭の片隅に入れておいて頂ければ。

2024-05-27 09:31 UTC, nobuchi commented on packages/frontend/remix/src/components/common/PlatCell/PlatCell.tsx
> +};
> このラッピング、ほとんど意味を成していないので不要な感じがします。
> 
> 直接 new Date() でよさそう。

@para7 

こちら修正しました！

2024-05-30 00:58 UTC, para7 commented
@nobuchi 
https://github.com/stlatica/stlatica/pull/453/commits/4a313ae1c5c51f70bb97a719e7c3a6de5a3d6952?short_path=7a491c5#diff-d20d4fba549f1416fe4b096c490d20680fe3427fc318fc116fad2910bb6b8aa3
このコミットで発生しているVRTファイル周りの変更が気になる（見えない）のですが、なんでしょう？

2024-05-31 13:15 UTC, nobuchi commented
> @nobuchi [4a313ae?short_path=7a491c5#diff-d20d4fba549f1416fe4b096c490d20680fe3427fc318fc116fad2910bb6b8aa3](https://github.com/stlatica/stlatica/commit/4a313ae1c5c51f70bb97a719e7c3a6de5a3d6952?short_path=7a491c5#diff-d20d4fba549f1416fe4b096c490d20680fe3427fc318fc116fad2910bb6b8aa3) このコミットで発生しているVRTファイル周りの変更が気になる（見えない）のですが、なんでしょう？

@para7 

vrt/updateをかけたときに発生したファイル変更です。
ビジュアルリグレッションテストをあまり理解できていないので、CIを通すためにvrt/updateをかけるとき、既存のスナップショットを全削除しているためこの変更が発生しているのだと思います。

やはり使い方を間違えているでしょうか...

2024-06-04 09:09 UTC, para7 approved these changes
vrtの件は定例で確認し、認識違いを修正出来たのでOK

結果としては運用に間違いがあったので正しい方法に矯正してもらった

2024-06-04 09:10 UTC, merged