PR：platを投稿した相対時間（ｎ分前...）を計算する関数の作成
stlatica/stlatica pull request #468
Opened 2024-06-16 13:39 UTC by nobuchi

# Issue

Closes #462 

# Overview

Date型を引数にとって、その相対時間を文字列で返す関数を作成しました。

`type PlatDateFormatter = (args: {platTimestamp: Date, currentTime: Date}) => string`

表示の種類：n秒前、n分前、n時間前、n日前、nヶ月前、n年前

---

platTimestamp の 日付が currentTime の日付を超えてしまう際はエラーを返すようにしています。

```
  const diff = args.currentTime.getTime() - args.platTimestamp.getTime();

  if (diff < 0) {
    throw new Error("Invalid time difference: platTimestamp is later than currentTime.");
  }
```

---

参考）[【TypeScript】2つの日時データの差を、日・時・分・秒に分けて求める #TypeScript - Qiita](https://qiita.com/Yu-Naka/items/e23fc3a8977da4615d39)

# Operation Verification

# Check List

- [x] セルフレビューをした(must)
- [ ] テストコードを記載した
- [ ] 動作検証の結果を記載した
- [ ] 関連するドキュメントの更新をした
- [x] 適切なLabelを設定した(e.g. frontend, documentation)

# Others

2024-06-16 16:33 UTC, para7 requested changes
@nobuchi 

確認修正お願いします！

また、vrtの修正を行いましたので main ブランチを取り込みお願いします！

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.ts
> +  }
一ヶ月は30日固定ではないので、ここはちょっと気になる部分ではありますね。

まあ正直私はこの仕様でもいい気はしますが、日付計算は一般的な処理なうえにコーナーケースが多い分野ですので、ライブラリに頼ることでスマートに解決できるかもしれません。

---

日付計算は有名なものがいくつかありますが、個人的おすすめは date-fns。今回のユースケースとも合致しています。

https://date-fns.org/

ライブラリ側の動作まではまだ見てないので実際どう計算されるかはわからないのですが、 もし date-fns を使うことで月ごとの日付差分まで吸収してくれるようであれば、ライブラリ実装に置き換えた方がよさそうです。

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.test.ts
> +  });
このケースですが、ブラウザ側時刻がずれていた場合は通常運用で起きうるので、異常系ではなく準正常系として捌いてください。

twitter だと「現在」表示になるようなので一旦それでお願いします

```suggestion
  test("不正な引数：タイムスタンプが現在時刻を超過", () => {
    expect(() => {
      PlatDateFormatter({
        platTimestamp: new Date("2021-01-30T00:00:55+09:00"),
        currentTime: new Date("2021-01-30T00:00:54+09:00"),
      });
    }).toBe("現在");
  });
```

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.test.ts
> +        platTimestamp: new Date("2021-01-30T00:00:55+09:00"),
テストケースが 55秒 だと視認性が悪いので、すべての数字に関して、できるだけキリのいい数字の方が好ましいですね。

たとえばですが

```
29
30
```

と

```
54
55
```

でそれぞれ並んでいるとき、前者は十の位も変化しているので視認性が高いのに対し、後者は1の位しか変化していないので見づらい、というのが視認性の良い悪いの感覚になります。

```suggestion
        platTimestamp: new Date("2020-01-01T00:00:00+09:00"),
```

※全部 00だと不都合あるケースあると思うので適宜調整してください。

---

もちろん、55秒に何かしらの意図があるのであれば、このままで問題ありません。

その場合はファイルの頭にコメント書いといてもらえるとありがたいです！

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.test.ts
> +    ).toBe("0 秒前");
0秒前は「現在」に吸収しちゃったほうがよさそうですね。

条件式が複雑にならなければ対応お願いします！

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.test.ts
> +        platTimestamp: new Date("2021-01-05T20:55:55+09:00"),
platTimestamp が途中から変わっていますが、できるだけテストケース全体で基準時刻は統一したほうが見やすいので、特にテスト上の意味がなければ統一をお願いします！

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.test.ts
> +    ).toBe("1 分前");
1のあと59に飛んでますが、2もあるといいかもです。

（ただし、1分と2分の境目として 1分59秒.... とかはまではやらなくていいです。このモジュールにそこまでの厳密性は不要なため。）

2024-06-16 16:33 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.ts
> + * @returns
未使用の jsdoc は削除お願いします

```suggestion
```

2024-06-29 19:28 UTC, nobuchi commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.ts
> +  }
@para7 

[こちらの記事](https://qiita.com/charon1212/items/5c68f408e1ea4b5e8da9#intervaltoduration)を読んだところ、今回使えそうな関数は intervalToDuration と isThis** のように思いました。

私の最初の実装だと、

- 1月1日と1月31日の差分：1ヶ月前
- 1月31日と3月1日の差分：29日前

と表示されます。これを 30日前 、1ヶ月前と表示するように修正すべき、という問題意識で正しいでしょうか？
そうであれば isThis** 関数を使えば実装できそうです。

---

date-fnsをインストールするときは、`/packages/frontend/remix`にて`pnpm install date-fns` でしょうか？こちらを行ったところ以下のエラーが出たのですが、store locationとは何でしょうか？

```
 ERR_PNPM_UNEXPECTED_STORE  Unexpected store location

The dependencies at "/home/nobuchi/Documents/stlatica/packages/frontend/remix/node_modules" are currently linked from the store at "/app/packages/frontend/remix/.pnpm-store/v3".

pnpm now wants to use the store at "/home/nobuchi/.local/share/pnpm/store/v3" to link dependencies.

If you want to use the new store location, reinstall your dependencies with "pnpm install".

You may change the global store location by running "pnpm config set store-dir <dir> --global".
(This error may happen if the node_modules was installed with a different major version of pnpm)
```

2024-06-30 12:08 UTC, para7 commented on packages/frontend/remix/src/components/common/PlatCell/PlatDateFormatter.ts
> +  }
> 1月1日と1月31日の差分：1ヶ月前
> 1月31日と3月1日の差分：29日前
>
> と表示されます。これを 30日前 、1ヶ月前と表示するように修正すべき、という問題意識で正しいでしょうか？

はい、そうです。
厄介な問題なので手実装するぐらいなら現状の実装のままでいいと思いますが、ライブラリですぐ直せそうなら直しておくほうがよいですね。

---

> date-fnsをインストールするときは、/packages/frontend/remixにてpnpm install date-fns でしょうか？こちらを行ったところ以下のエラーが出たのですが、store locationとは何でしょうか？

> /home/nobuchi/.local/share/pnpm/store/v3

ローカルのパスが出てるので、 docker で pnpm install したものとホスト側で pnpm install したものがぶつかっているように見えます。
とりあえず node_modules を削除してインストールし直したら解決しませんか？

2024-07-06 20:25 UTC, nobuchi commented
@para7 

以下対応しました。ご確認お願いします！

月の日数に関して、今回はライブラリなし30日固定の実装とさせてください。

> このケースですが、ブラウザ側時刻がずれていた場合は通常運用で起きうるので、異常系ではなく準正常系として捌いてください。
> 
> twitter だと「現在」表示になるようなので一旦それでお願いします

> 0秒前は「現在」に吸収しちゃったほうがよさそうですね。
> 
> 条件式が複雑にならなければ対応お願いします！

超過、同時刻のケースに「現在」の文字列を返すよう修正

> テストケースが 55秒 だと視認性が悪いので、すべての数字に関して、できるだけキリのいい数字の方が好ましいですね。

> platTimestamp が途中から変わっていますが、できるだけテストケース全体で基準時刻は統一したほうが見やすいので、特にテスト上の意味がなければ統一をお願いします！

`platTimestamp: new Date("2020-01-01T00:00:00+09:00")` に統一

> 1のあと59に飛んでますが、2もあるといいかもです。
> 
> （ただし、1分と2分の境目として 1分59秒.... とかはまではやらなくていいです。このモジュールにそこまでの厳密性は不要なため。）

年以外のすべての単位に2のケースを追加

> 未使用の jsdoc は削除お願いします

削除

2024-07-10 09:54 UTC, para7 approved these changes
@nobuchi 
いい感じです。ありがとうございます！

30日のほうは了解です。数値がおかしくなるわけではないのでこれでOKです！

2024-07-13 17:15 UTC, merged